### ISSUE TITLE
ProtoDataStream to work as cursor

### ISSUE THREAD

**Issue by alex-parfenyuk** [rdingwall/protobuf-net-data#30]
We have the following scenario:

-Service and Client on the same box and using net.pipe binding to talk to each other
-service reads a huge DataTable that could be ~4Gb or even more
-consumer needs to receive this DataTable
-the communication happens using WCF contract like Stream GetData()
-we are using ProtoBuf.Data.ProtoDataStream for table serialization/deserialization

The problem:
- both client and server are on one box so there are times when the RAM used by DataTable is doubled.

If there a way to read from the service and delete read data on a service side ?

**Comment by rdingwall** [comment]
Hi @alex-parfenyuk, yes, don't use DataTable because it will buffer the entire result set. Use IDataReader instead.

**Comment by rdingwall** [comment]
All of the APIs (DataSerializer, IDataSerializerEngine, IProtoDataWriter, ProtoDataReader) support IDataReader. You do not need a DataTable anywhere to use protobuf-net-data.
