### ISSUE TITLE
We need Metadata also.

### ISSUE THREAD

**Issue by softboy99** [rdingwall/protobuf-net-data#31]
Metadata about unique keys, auto increment, default value, base table name, data provider, data relations etc is ignored

**Comment by rdingwall** [comment]
Hi @softboy99, protobuf-net-data is a library for seriaizing *portable* tabular data. It is not intended to be a full serialization of all of ADO.NET's features. You can use the built-in CLR binary serialization or XML for that.

**Comment by softboy99** [comment]
Hi,
your answer is so officail, of course, we can sue built-in on. Howerver, if there is no other technichal considrations, where there's so many third party libray? Just for money? Of cause not.
